
include: "../common/common.smk"
import os
from pathlib import Path
from snakemake.logging import logger

outdir = config.get("outdir", "output")
logdir = config.get("logdir", "logs")
populations = config.get("populations", {})
pop_names = sorted(populations)

rule population_metadata:
    output:
        popmap = outdir + "/metadata/population.tsv",
        popfiles = [outdir + "/metadata/populations/" + pop + ".txt" for pop in pop_names]
    log:
        logdir + "/population_metadata.log"
    run:
        log_path = str(log)
        os.makedirs(os.path.dirname(log_path), exist_ok=True)
        with open(log_path, "w") as handle:
            handle.write("population metadata is generated by Python\n")
        os.makedirs(os.path.dirname(output.popmap), exist_ok=True)
        with open(output.popmap, "w") as handle:
            handle.write("sample\tpopulation\n")
            for population in pop_names:
                for sample in populations[population]:
                    handle.write(f"{sample}\t{population}\n")
        for population, path in zip(pop_names, output.popfiles):
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as handle:
                handle.write("\n".join(populations[population]) + "\n")
